
openapi: 3.0.3
info:
  title: MarketData Service API
  description: MarketData Service API
  version: 1.0.0
servers:
  - url: "[[${env.marketdata-service-url}]]"
    description: XXX
externalDocs:
  - url: "[[${env.marketdata-service-documentation-url}]]"

tags:
  - rateCurve
  - fxSpot
  - fxForward
  - fxVolatility


paths:
  /fxSpot/{currencyPair}/{dateFrom}/{dateTo}:
    get:
      tags:
        - fxSpot
      summary: get a list of FX spot for a given currency pair list and a list of date
      operationId: getFxSpot
      parameters:
        - in: path
          name: currencyPair
          required: true
          schema:
            type: string
          description: the currency pair
          example: EUR-USD

        - in: path
          name: dateFrom
          required: true
          schema:
            type: string
            format: date
          description: the date or the from date
          example: 2022-01-15

        - in: path
          name: dateTo
          required: false
          schema:
            type: string
            format: date
          description: the to date
          example: 2023-02-17

      responses:
        '200':
          description: FX Spot successfully retrieved
          content:
            application/valuation+json:
              schema:
                $ref: '#/components/schemas/FXSpotDTO'

      default:
        description: unexpected error
        content:
          application/problem+json:
            schema:
              $ref: '#/components/schemas/ProblemDTO'

  /fxSpot/search:
    post:
      tags:
        - fxSpot
      summary: Search a List of FX spot for a given criteria
      operationId: searchFxSpots
      requestBody:
        content:
          application/vnd.ams.fxSpot-search-api+json:
            schema:
              $ref: '#/components/schemas/FXSpotSearchDTO'
        required: true
      responses:
        '200':
          description: Successfully returned a list with fxSpots matching search criteria
          content:
            application/vnd.ams.cds-curve-search-api.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FXSpotDTO'
        '400':
          description: Invalid status value
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'
        default:
          description: unexpected error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'
  /fxSpot/synchronize:
    post:
      tags:
        - fxSpot
      summary: Synchronize fx spots from XXX for a given criteria
      operationId: synchronizeFxSpots
      requestBody:
        content:
          application/vnd.ams.fxSpot-synchronize-api+json:
            schema:
              $ref: '#/components/schemas/FXSpotSynchronizeDTO'
        required: true
      parameters:
        - in: query
          name: provider
          description: where to search for fxSpots
          example: 'BBG'
          schema:
            type: string
            enum:
              - BBG
              - Binance
        - in: query
          name: publish
          description: whether to publish the fxSpots
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Grabbing fxSpots from XXX a list with cds curves matching search criteria
          content:
            application/vnd.ams.fxspot-search-api.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FXSpotDTO'
        '400':
          description: Invalid status value
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'
        default:
          description: unexpected error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'
  /fxSpot:
    post:
      tags:
        - fxSpot
      summary: Update a FX spot for a given currency pair and a date
      operationId: updateFxSpot
      requestBody:
        content:
          application/vnd.ams.fxSpot-search-api+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/FXSpotDTO'

      responses:
        '200':
          description: FX Spot successfully updated
          content:
            application/valuation+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FXSpotDTO'

        '400':
          description: Invalid status value
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'
        default:
          description: unexpected error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'

    get:
      tags:
        -fxSpot
      summary: get all fxSpots
      operationId: getAllFxSpots
      responses:
        '200':
          description: FX Spot successfully retrieved
          content:
            application/valuation+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FXSpotDTO'

  /fxVolatility/synchronize:
    post:
      tags:
        - fxVolatility
      summary: Synchronize volatility spots from XXX for a given criteria
      operationId: synchronizeFxVolatility
      requestBody:
        content:
          application/vnd.ams.fxVolatility-synchronize-api+json:
            schema:
              $ref: '#/components/schemas/FXSpotSynchronizeDTO'
        required: true
      parameters:
        - in: query
          name: provider
          description: where to search for fxVolatility
          example: 'BBG'
          schema:
            type: string
            enum:
              - BBG
              - Binance
        - in: query
          name: publish
          description: whether to publish the fxVolatility
          schema:
            type: boolean
            default: false
      responses:
        '200':
          description: Grabbing fxVolatility from XXX
          content:
            application/vnd.ams.fxVolatility-search-api.v2+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FXSpotDTO'
        '400':
          description: Invalid status value
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'
        default:
          description: unexpected error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'


components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:

    FXSpotDTO:
      type: object
      properties:
        curr1:
          type: string
          minLength: 3
          maxLength: 3
          example: EUR
        curr2:
          type: string
          minLength: 3
          maxLength: 3
          example: USD
        date:
          type: string
          format: date
          example: 2022-11-25
        value:
          type: number
          format: double
          minimum: 0
          example: 2.5
      required:
        - curr1
        - curr2
        - date
        - value

    FXSpotSearchDTO:
      type: object
      properties:
        curr1:
          type: string
          minLength: 3
          maxLength: 3
          example: EUR
        curr2:
          type: string
          minLength: 3
          maxLength: 3
          example: USD
        date:
          type: string
          format: date
          example: 2022-11-25
        required:
          - curr1
          - curr2

    FXSpotSynchronizeDTO:
      type: object
      properties:
        curr1:
          type: string
          minLength: 3
          maxLength: 3
          example: EUR
        curr2:
          type: string
          minLength: 3
          maxLength: 3
          example: USD
        date:
          type: string
          format: date
          example: 2022-11-25
        required:
          - curr1
          - curr2
          - date

    ProblemDTO:
      type: object
      required:
        - code
      properties:
        code:
          type: string


