apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-service
spec:
  selector:
    matchLabels:
      app: health-service
  replicas: 1
  template:
    metadata:
      labels:
        app: health-service
    spec:
      containers:
        - name: health-service
          image: mhoutreille/health-service:latest
          ports:
            - containerPort: 8090
          livenessProbe:
            httpGet:
              path: /hello
              port: 8090
          readinessProbe:
            httpGet:
              path: /hello
              port: 8090