server:
  port: 8081

spring:
  datasource:
    ##url: jdbc:h2:mem:testdb
    ##url: jdbc:h2:file:./data/demo
    ##driver-class-name: org.h2.Driver
    ##username: sa
    ##password: password

    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=marketdata_service
    username: marketdata_service_user
    password: marketdata_service_pwd123

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        hibernateFormatSql: true

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    check-location: true
    clean-disabled: false
    enabled: true
    table: flyway_schema_history
    clean-on-validation-error: true