
openapi: 3.0.3
info:
  title: Financial Service API
  description: Financial Service API
  version: 1.0.0
servers:
  - url: "[[${env.financial-service-url}]]"
    description: XXX
externalDocs:
  - url: "[[${env.financial-service-documentation-url}]]"

tags:
  - VanillaFXOptionPricing
  - Test

paths:
  /test:
    get:
      tags:
        - Test
      summary: Test
      description: Test
      operationId: getTest


  /option/fx/vanilla:
    post:
      tags:
        - VanillaFXOptionPricing
      summary: Vanilla FX Option Pricing
      description: Launch Vanilla FX Option Pricing
      operationId: vanillaFxOptionPricing
      requestBody:
        content:
          application/vnd.eblood.option-pricing-api+json:
            schema:
              $ref: '#/components/schemas/FXOptionDTO'
        required: true

      responses:
        '200':
          description: Vanilla FX Option successfully priced
          content:
            application/valuation+json:
              schema:
                $ref: '#/components/schemas/ValuationDTO'

        '400':
          description: Invalid status value
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'
        default:
          description: unexpected error
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDTO'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

  schemas:

    FXOptionDTO:
      type: object
      properties:
        curr1:
          type: string
          minLength: 3
          maxLength: 3
          example: EUR
        curr2:
          type: string
          minLength: 3
          maxLength: 3
          example: USD
        maturityDate:
          type: string
          format: date
          example: 2022-11-25
        strike:
          type: number
          format: double
          minimum: 0
          example: 2.5
        valuationDate:
          type: string
          format: date
          example: 2022-11-25
        pricingMethod:
          type: string
          enum:
            - BSClosedFormula
            - BSMonteCarlo
          default: BSClosedFormula
      required:
        - curr1
        - curr2
        - maturityDate
        - strike
        - valuationDate

    ValuationDTO:
      type: object
      properties:
        value:
          type: number
          format: double
        valuationDate:
          type: string
          format: date
        currency:
          type: string
          example: USD


    ProblemDTO:
      type: object
      required:
        - code
      properties:
        code:
          type: string


